import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const pkgDir = new URL("../node_modules/@visioncortex/vtracer/", import.meta.url);
const upstreamVersion = require("@visioncortex/vtracer/package.json").version;

const GLUE_IN = new URL("pkg/vtracer_wasm.js", pkgDir);
const WASM_IN = new URL("pkg/vtracer_wasm_bg.wasm", pkgDir);
const OUT_DIR = new URL("../vendor/", import.meta.url);

const NODE_LOADER = `const wasmPath = \`\${__dirname}/vtracer_wasm_bg.wasm\`;
const wasmBytes = require('fs').readFileSync(wasmPath);
const wasmModule = new WebAssembly.Module(wasmBytes);
let wasmInstance = new WebAssembly.Instance(wasmModule, __wbg_get_imports());
let wasm = wasmInstance.exports;
wasm.__wbindgen_start();`;

const BROWSER_LOADER = `// --- vendored for the browser, see scripts/vendor.mjs ---
// Upstream loads the binary with fs.readFileSync at module scope. Here it is
// fetched on demand instead, so a page that carries this script pays nothing
// until somebody actually traces an image - the binary is over half a
// megabyte and most visitors will never use the tool.
let wasm;

export function isReady() {
  return wasm !== undefined;
}

export async function init(wasmUrl) {
  if (wasm !== undefined) return;
  const response = await fetch(wasmUrl);
  if (!response.ok) {
    throw new Error(\`could not load the tracing engine (\${response.status})\`);
  }
  let instance;
  try {
    // Streaming needs the server to send application/wasm. Plenty do not, and
    // the failure is an obscure TypeError, so fall back rather than break on
    // somebody else's Content-Type header.
    ({ instance } = await WebAssembly.instantiateStreaming(response.clone(), __wbg_get_imports()));
  } catch {
    const bytes = await response.arrayBuffer();
    ({ instance } = await WebAssembly.instantiate(bytes, __wbg_get_imports()));
  }
  wasm = instance.exports;
  wasm.__wbindgen_start();
}`;

const EXPORTS = [
  ["exports.vectorize_bytes = vectorize_bytes;", "export { vectorize_bytes };"],
  ["exports.vectorize_rgba = vectorize_rgba;", "export { vectorize_rgba };"],
];

const source = await readFile(GLUE_IN, "utf8");

if (!source.includes(NODE_LOADER)) {
  throw new Error(
    `The upstream loader in @visioncortex/vtracer@${upstreamVersion} is not what this script ` +
      "expects. It has changed shape, so the replacement would produce a module that never " +
      "instantiates. Re-read pkg/vtracer_wasm.js and update NODE_LOADER before shipping.",
  );
}

let out = source.replace(NODE_LOADER, BROWSER_LOADER);

for (const [from, to] of EXPORTS) {
  if (!out.includes(from)) {
    throw new Error(`Upstream no longer exports via "${from}". Vendoring aborted.`);
  }
  out = out.replace(from, to);
}

const remaining = out.match(/\brequire\s*\(/g);
if (remaining) {
  throw new Error(`${remaining.length} require() call(s) still in the vendored glue.`);
}

const banner = `/* Vendored from @visioncortex/vtracer@${upstreamVersion} (MIT OR Apache-2.0)
 * https://github.com/visioncortex/vtracer
 *
 * Generated by scripts/vendor.mjs. Do not edit by hand - re-run \`npm run vendor\`.
 * The only change from upstream is the loader: fs.readFileSync at module scope
 * becomes an async fetch, so this runs in a browser and loads on demand.
 */
`;

await mkdir(OUT_DIR, { recursive: true });
await writeFile(new URL("vtracer_wasm.js", OUT_DIR), banner + out);
await copyFile(WASM_IN, new URL("vtracer_wasm_bg.wasm", OUT_DIR));
await writeFile(
  new URL("UPSTREAM.txt", OUT_DIR),
  [
    `@visioncortex/vtracer@${upstreamVersion}`,
    "MIT OR Apache-2.0",
    "https://github.com/visioncortex/vtracer",
    "",
    "vtracer_wasm_bg.wasm is upstream's binary, copied unmodified.",
    "vtracer_wasm.js is upstream's glue with the Node loader replaced by a",
    "browser fetch. Regenerate both with `npm run vendor`.",
    "",
  ].join("\n"),
);

console.log(`vendored vtracer ${upstreamVersion}`);
